export const NAVARASAS = {
  shringara: {
    name: 'Shringara',
    sanskrit: 'श्रृंगार',
    english: 'Love & Beauty',
    emoji: '💕',
    color: '#FF69B4',
    gradient: 'from-pink-400 to-rose-500',
    description: 'The emotion of love, beauty, and romantic attraction. Music with soft melodies, moderate tempo, and smooth transitions evokes this rasa.',
    characteristics: ['Soft melodies', 'Romantic themes', 'Smooth transitions', 'Moderate tempo'],
  },
  hasya: {
    name: 'Hasya',
    sanskrit: 'हास्य',
    english: 'Joy & Laughter',
    emoji: '😄',
    color: '#FFD700',
    gradient: 'from-yellow-400 to-orange-500',
    description: 'The emotion of joy, happiness, and laughter. Upbeat music with high energy, fast tempo, and bright tones represents this rasa.',
    characteristics: ['Upbeat rhythm', 'Fast tempo', 'High energy', 'Bright tones'],
  },
  karuna: {
    name: 'Karuna',
    sanskrit: 'करुणा',
    english: 'Sadness & Compassion',
    emoji: '😢',
    color: '#4169E1',
    gradient: 'from-blue-400 to-indigo-600',
    description: 'The emotion of sadness, sorrow, and compassion. Slow tempo, minor keys, and low energy characterize music evoking this rasa.',
    characteristics: ['Slow tempo', 'Minor keys', 'Low energy', 'Melancholic tones'],
  },
  raudra: {
    name: 'Raudra',
    sanskrit: 'रौद्र',
    english: 'Anger & Fury',
    emoji: '😠',
    color: '#DC143C',
    gradient: 'from-red-500 to-crimson-700',
    description: 'The emotion of anger, rage, and fury. Heavy percussion, high energy, aggressive tones, and dissonance define this rasa.',
    characteristics: ['Heavy percussion', 'Aggressive tones', 'High intensity', 'Dissonant harmonies'],
  },
  veera: {
    name: 'Veera',
    sanskrit: 'वीर',
    english: 'Courage & Heroism',
    emoji: '💪',
    color: '#FF4500',
    gradient: 'from-orange-500 to-red-600',
    description: 'The emotion of courage, heroism, and valor. Bold rhythms, strong beats, powerful melodies, and ascending patterns embody this rasa.',
    characteristics: ['Bold rhythm', 'Strong beats', 'Powerful melodies', 'Triumphant themes'],
  },
  bhayanaka: {
    name: 'Bhayanaka',
    sanskrit: 'भयानक',
    english: 'Fear & Terror',
    emoji: '😱',
    color: '#800080',
    gradient: 'from-purple-600 to-indigo-900',
    description: 'The emotion of fear, terror, and anxiety. Irregular rhythm, sudden changes, suspenseful tones, and unsettling patterns create this rasa.',
    characteristics: ['Irregular rhythm', 'Suspenseful tones', 'Sudden changes', 'Unsettling patterns'],
  },
  bibhatsa: {
    name: 'Bibhatsa',
    sanskrit: 'बीभत्स',
    english: 'Disgust & Aversion',
    emoji: '🤢',
    color: '#228B22',
    gradient: 'from-green-600 to-emerald-800',
    description: 'The emotion of disgust, aversion, and repulsion. Harsh tones, jarring transitions, and dissonant harmonies evoke this rasa.',
    characteristics: ['Harsh tones', 'Jarring transitions', 'Dissonance', 'Unpleasant textures'],
  },
  adbhuta: {
    name: 'Adbhuta',
    sanskrit: 'अद्भुत',
    english: 'Wonder & Surprise',
    emoji: '😲',
    color: '#00CED1',
    gradient: 'from-cyan-400 to-teal-600',
    description: 'The emotion of wonder, surprise, and amazement. Dynamic changes, unexpected patterns, and ethereal tones characterize this rasa.',
    characteristics: ['Dynamic changes', 'Unexpected patterns', 'Ethereal tones', 'Surprising elements'],
  },
  shanta: {
    name: 'Shanta',
    sanskrit: 'शान्त',
    english: 'Peace & Tranquility',
    emoji: '🕉️',
    color: '#98FB98',
    gradient: 'from-green-300 to-emerald-400',
    description: 'The emotion of peace, tranquility, and serenity. Slow tempo, consistent rhythm, and harmonious tones create this meditative rasa.',
    characteristics: ['Slow tempo', 'Consistent rhythm', 'Harmonious tones', 'Meditative quality'],
  },
}

export const SUPPORTED_FORMATS = ['.mp3', '.wav', '.flac', '.ogg']
export const MAX_FILE_SIZE = 10 * 1024 * 1024 // 10MB

export const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000/api'
export const ML_SERVICE_URL = import.meta.env.VITE_ML_SERVICE_URL || 'http://localhost:8000'
